trait_upload_homepage:
    path:     /
    defaults: { _controller: "TraitUploadBundle:Default:defaultTemplate" }

trait_upload_index:
    path:     /index
    defaults: { _controller: "TraitUploadBundle:Default:index" }

trait_upload_show:
    path:     /{id}/show
    defaults: { _controller: "TraitUploadBundle:Default:show" }
    methods:  GET

trait_upload_new:
    path:     /new
    defaults: { _controller: "TraitUploadBundle:Default:new" }
    methods:  [GET, POST]

trait_upload_edit:
    path:     /{id}/edit
    defaults: { _controller: "TraitUploadBundle:Default:edit" }
    methods:  [GET, POST]

trait_upload_delete:
    path:     /{id}/delete
    defaults: { _controller: "TraitUploadBundle:Default:delete" }
    methods:  DELETE